CREATE TABLE KLADR (
	NAME VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
    SOCR VARCHAR(10),
	CODE VARCHAR(13) PRIMARY KEY,
	POSTINDEX VARCHAR(6),
	GNINMB VARCHAR(4),
	UNO VARCHAR(4),
	OCATD VARCHAR(11),
	STATUS VARCHAR(1)
) TYPE MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE STREET (
  NAME VARCHAR(40),
  SOCR VARCHAR(10),
  CODE VARCHAR(17) PRIMARY KEY,
  POSTINDEX VARCHAR(6),
  GNINMB VARCHAR(4),
  UNO VARCHAR(4),
  OCATD VARCHAR(11)
) TYPE MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE DOMA (
  NAME VARCHAR(40),
  KORP VARCHAR(10),
  SOCR VARCHAR(10),
  CODE VARCHAR(19) PRIMARY KEY,
  POSTINDEX	VARCHAR(6),
  GNINMB VARCHAR(4),
  UNO	VARCHAR(4),
  OCATD VARCHAR(11)
) TYPE MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE FLAT (
  NAME VARCHAR(40),
  CODE VARCHAR(23) PRIMARY KEY,
  POSTINDEX VARCHAR(6),
  GNINMB VARCHAR(4),
  UNO VARCHAR(4),
  NP VARCHAR(4)
) TYPE MYISAM;

CREATE TABLE SOCRBASE (
  LEVEL VARCHAR(5),
  SCNAME VARCHAR(10),
  SOCRNAME VARCHAR(29),
  KOD_T_ST VARCHAR(3) PRIMARY KEY
) TYPE MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE ALTNAMES (
  OLDCODE VARCHAR(19) PRIMARY KEY,
  NEWCODE VARCHAR(19),
  LEVEL VARCHAR(1)
) TYPE MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;

COMMIT;

