//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.02 at 01:20:07 AM MSK 
//


package com.emal.kladr.webservice.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.emal.kladr.webservice.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegionsRequest_QNAME = new QName("http://emal.com/kladr/schemas", "RegionsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.emal.kladr.webservice.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StreetRequest }
     * 
     */
    public StreetRequest createStreetRequest() {
        return new StreetRequest();
    }

    /**
     * Create an instance of {@link KladrResponse }
     * 
     */
    public KladrResponse createKladrResponse() {
        return new KladrResponse();
    }

    /**
     * Create an instance of {@link Street }
     * 
     */
    public Street createStreet() {
        return new Street();
    }

    /**
     * Create an instance of {@link LocalitiesRequest }
     * 
     */
    public LocalitiesRequest createLocalitiesRequest() {
        return new LocalitiesRequest();
    }

    /**
     * Create an instance of {@link StreetResponse }
     * 
     */
    public StreetResponse createStreetResponse() {
        return new StreetResponse();
    }

    /**
     * Create an instance of {@link Kladr }
     * 
     */
    public Kladr createKladr() {
        return new Kladr();
    }

    /**
     * Create an instance of {@link DistrictsRequest }
     * 
     */
    public DistrictsRequest createDistrictsRequest() {
        return new DistrictsRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://emal.com/kladr/schemas", name = "RegionsRequest")
    public JAXBElement<Object> createRegionsRequest(Object value) {
        return new JAXBElement<Object>(_RegionsRequest_QNAME, Object.class, null, value);
    }

}
